# Generated by Django 2.2.10 on 2020-02-24 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habits_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='priority',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
