# Generated by Django 2.2.10 on 2020-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200224_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
