# Generated by Django 2.2.10 on 2020-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20200225_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
