# Generated by Django 2.2.10 on 2020-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20200225_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='implement',
            field=models.BooleanField(default=False),
        ),
    ]
