# Generated by Django 2.2.10 on 2020-03-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habits_implement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='days',
        ),
    ]
