# Generated by Django 2.2.10 on 2020-03-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_habits_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
