# Generated by Django 2.2.10 on 2020-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biggest_strike',
            new_name='longest_strike',
        ),
    ]
