# Generated by Django 2.2.10 on 2020-02-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200224_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='strike',
            new_name='current_strike_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='task_quantity',
            new_name='habits_quantity',
        ),
    ]
