# Generated by Django 2.2.10 on 2020-02-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailconfirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmed',
        ),
    ]
