# Generated by Django 2.2.10 on 2020-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_emailconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='did_all_habits',
            field=models.BooleanField(default=False),
        ),
    ]
